services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/docuquery
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docuquery123
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_URL=http://chromadb:8000
    depends_on:
      - postgres
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma

  postgres:
    image: postgres:16
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: docuquery
      POSTGRES_PASSWORD: docuquery123
    volumes:
      - pg-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  chroma-data:
  pg-data: