spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/docuquery
    username: postgres
    password: docuquery123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

openai:
  api-key: ${OPENAI_API_KEY}
  embedding-model: text-embedding-3-small
  chat-model: gpt-4o-mini

chromadb:
  url: ${CHROMADB_URL:http://localhost:8000}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always